version: "3"
services:
  opus-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    ports:
      - ${OPUS_HTTP_PORT}:${OPUS_HTTP_PORT}
      - ${OPUS_ADMIN_PORT}:${OPUS_ADMIN_PORT}
    entrypoint: /bin/bash
    command: [
        "-c",
          "aca-py start \
          --inbound-transport http '0.0.0.0' ${OPUS_HTTP_PORT} \
          --outbound-transport http \
          --endpoint ${OPUS_AGENT_ENDPOINT} \
          --webhook-url ${OPUS_WEBHOOK_URL} \
          --wallet-type 'indy' \
          --seed '${OPUS_WALLET_SEED}' \
          --admin '0.0.0.0' ${OPUS_ADMIN_PORT} \
          --admin-insecure-mode \
          --log-level info \
          --label ${OPUS_AGENT_NAME}",
        ]
  opus-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - opus-agent
    ports:
      - 5000:5000
      - ${OPUS_WEBHOOK_PORT}:${OPUS_WEBHOOK_PORT}
    entrypoint: /bin/bash
    command:
      [
        "-c",
        "sleep 2;
        python ./server.py"
      ]
