version: "3"
services:
  alice-agent:
    image: alice-protocol:agent
    build:
      context: ../../
      dockerfile: tutorials/dockerfiles/Dockerfile.attachmentprotocol
    ports:
      - ${ALICE_HTTP_PORT}:${ALICE_HTTP_PORT}
      - ${ALICE_ADMIN_PORT}:${ALICE_ADMIN_PORT}
    networks:
      - indy_demo
    entrypoint: /bin/bash
    command: [
        "-c",
        "
          sleep 5;
          aca-py start \
          --inbound-transport http '0.0.0.0' ${ALICE_HTTP_PORT} \
          --outbound-transport http \
          --endpoint ${ALICE_AGENT_ENDPOINT} \
          --webhook-url ${ALICE_WEBHOOK_URL} \
          --wallet-type 'indy' \
          --seed '${ALICE_WALLET_SEED}' \
          --admin '0.0.0.0' ${ALICE_ADMIN_PORT} \
          --plugin attach_protocol.attachment_protocol \
          --admin-insecure-mode \
          --log-level info \
          --label ${ALICE_AGENT_NAME}",
      ]
  bob-agent:
    image: bob-protocol:agent
    build:
      context: ../../
      dockerfile: tutorials/dockerfiles/Dockerfile.attachmentprotocol
    ports:
      - ${BOB_HTTP_PORT}:${BOB_HTTP_PORT}
      - ${BOB_ADMIN_PORT}:${BOB_ADMIN_PORT}
    networks:
      - indy_demo
    entrypoint: /bin/bash
    command: [
      "-c",
      "sleep 5;
      aca-py start \
         --inbound-transport http '0.0.0.0' ${BOB_HTTP_PORT} \
         --outbound-transport http \
         --endpoint ${BOB_AGENT_ENDPOINT} \
         --webhook-url ${BOB_WEBHOOK_URL} \
         --wallet-type 'indy' \
         --seed '${BOB_WALLET_SEED}' \
         --admin '0.0.0.0' ${BOB_ADMIN_PORT} \
         --admin-insecure-mode \
         --plugin attach_protocol.attachment_protocol \
         --log-level info \
         --label ${BOB_AGENT_NAME}",
    ]
  setup:
    build:
      context: ../../
      dockerfile: tutorials/helpers/create_connection/Dockerfile
    networks:
      - indy_demo
    depends_on:
      - alice-agent
      - bob-agent
#    ports:
#      - ${ALICE_WEBHOOK_PORT}:${ALICE_WEBHOOK_PORT}
#      - ${BOB_WEBHOOK_PORT}:${BOB_WEBHOOK_PORT}
    environment:
      - ALICE_ADMIN_URL=http://alice-agent:${ALICE_ADMIN_PORT}
      - ALICE_WEBHOOK_PORT=${ALICE_WEBHOOK_PORT}
      - ALICE_API_KEY=${ALICE_API_KEY}
      - ALICE_WEBHOOK_HOST=0.0.0.0
      - BOB_ADMIN_URL=http://bob-agent:${BOB_ADMIN_PORT}
      - BOB_WEBHOOK_PORT=${BOB_WEBHOOK_PORT}
      - BOB_WEBHOOK_HOST=0.0.0.0
    entrypoint: /bin/bash
    command:
      [
        "-c",
        "sleep 5;
        python ./create_connection.py"
      ]
  alice-notebook:
    build:
      context: ../../
      dockerfile: tutorials/attachments/Dockerfile
      args:
        - jupyter_port=${ALICE_JUPYTER_PORT}
    depends_on:
      - alice-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/notebooks/alice:/workspace
    ports:
      - "8888:8888"
      - ${ALICE_WEBHOOK_PORT}:${ALICE_WEBHOOK_PORT}
  bob-notebook:
    build:
      context: ../../
      dockerfile: tutorials/attachments/Dockerfile
      args:
        - jupyter_port=${BOB_JUPYTER_PORT}
    depends_on:
      - bob-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/notebooks/bob:/workspace
    ports:
      - "8889:8888"
      - ${BOB_WEBHOOK_PORT}:${BOB_WEBHOOK_PORT}

networks:
  indy_demo:
